### ISSUE TITLE
Symlinks in $WERCKER_OUTPUT_DIR are broken in deploy pipeline

### ISSUE THREAD

**Issue by Starefossen** [wercker/docs#310]
In the deploy pipeline the symlinks from `$WERCKER_OUTPUT_DIR` are broken. Here is a common example to reproduce:

```
box: node:latest                                         
                                                         
build:                                                   
    steps:                                               
        - npm-install                                    
                                                         
        - script:                                        
            name: list                                   
            code: ls -la node_modules/.bin                           
                                                                                                                  
deploy:                                                  
    steps:                                               
        - script:                                        
            name: list                        
            code: ls -la node_modules/.bin                           
```

**Comment by kbrownlees** [comment]
+1

This causes all sorts of pain if you try to move a python virtualenv between stages. It works for me locally, the way the tar is created in the hosted environment must be slightly different.

Example error:
```
Python version: 3.5.1 (default, Mar  9 2016, 03:30:07)  [GCC 4.9.2]
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ImportError: No module named 'encodings'
```

**Comment by turiphro** [comment]
We have the same problem.

**Comment by io-monad** [comment]
I've found a workaround for this problem.

You can re-create symlinks in node_modules/.bin by calling `npm rebuild`. So putting a simple script step will make everything fine.

Try this:

```yaml
deploy:
    steps:
        - script:
            name: npm rebuild
            code: npm rebuild

        - script:
            name: list 
            code: ls -la node_modules/.bin
```
