### ISSUE TITLE
Is there a tutorial of how to get docker toolbox to work or the docker terminal to work with wercker?

### ISSUE THREAD

**Issue by rlam3** [wercker/docs#396]
Is there a tutorial of how to get docker toolbox to work or the docker terminal to work with wercker? Please update the documentation with this approach if you could. Thanks!

**Comment by Tonnu** [comment]
This guide should get you started http://wercker.com/cli/install/

**Comment by rlam3** [comment]
Awesome man! Thanks! 

I'm running into the following problem with my pip install... now... However it works on my local environment...Is the way I'm setting up wercker.yml not correct? Thanks!


```txt
# requirement.txt

Babel==1.3
Flask==0.10.1
Flask-Babel==0.9
Flask-Login==0.2.11
Flask-Mail==0.9.0
Flask-Migrate==1.2.0
Flask-OpenID==1.2.1
Flask-SQLAlchemy==2.0
Flask-Script==2.0.5
Flask-WTF==0.9.4
Flask-WhooshAlchemy==0.56
Jinja2==2.8
Mako==1.0.0
MarkupSafe==0.23
SQLAlchemy==0.9.7
Tempita==0.5.2
WTForms==1.0.5
Werkzeug==0.11.3
Whoosh==2.6.0
alembic==0.6.7
blinker==1.3
decorator==3.4.0
dj-database-url==0.3.0
flask-wysiwyg==0.1
flup==1.0.2
gnureadline==6.3.3
gunicorn==19.1.1
ipython==2.2.0
itsdangerous==0.24
migrate==0.3.7
pbr==0.10.0
psycopg2==2.6.1
python-openid==2.2.5
pytz==2014.7
script==1.7.2
six==1.7.3
sorl-thumbnail==11.12
speaklater==1.3
sqlalchemy-migrate==0.9.1
wsgiref==0.1.2
```

```yml
#wercker.yml

box: python:2.7
# You can also use services such as databases. Read more on our dev center:
# http://devcenter.wercker.com/docs/services/index.html
# services:
    # - postgres
    # http://devcenter.wercker.com/docs/services/postgresql.html

    # - mongodb
    # http://devcenter.wercker.com/docs/services/mongodb.html

# This is the build pipeline. Pipelines are the core of wercker
# Read more about pipelines on our dev center
# http://devcenter.wercker.com/docs/pipelines/index.html
build:
  # The steps that will be executed on build
  # Steps make up the actions in your pipeline
  # Read more about steps on our dev center:
  # http://devcenter.wercker.com/docs/steps/index.html
  steps:
    # A step that sets up the python virtual environment
    - virtualenv:
        name: setup virtual environment
        install_wheel: false # Enable wheel to speed up builds (experimental)

    # A step that executes `pip install` command.
    - pip-install

    # A custom script step, name value is used in the UI
    # and the code value contains the command that get executed
    - script:
        name: echo python information
        code: |
          echo "python version $(python --version) running"
          echo "pip version $(pip --version) running"



```



```shell
wercker build

...

Collecting script==1.7.2 (from -r requirements.txt (line 35))
  Could not find a version that satisfies the requirement script==1.7.2 (from -r requirements.txt (line 35)) (from versions: )
No matching distribution found for script==1.7.2 (from -r requirements.txt (line 35))
failed: pip install failed
--> Step failed: pip-install 16.32s
--> Exported Cache: 1.16s
--> Pipeline failed: 398.57s
WARNING Box container has already stopped.
FATAL Step failed: pip-install
```
