### ISSUE TITLE
Cannot push to ECR

### ISSUE THREAD

**Issue by elhachmi** [wercker/docs#397]
It's very hard to find this:
```yml
box: busybox
push-to-ecr:
  steps:
    - internal/docker-push:
        aws-access-key: $AWS_ACCESS_KEY_ID
        aws-secret-key: $AWS_SECRET_ACCESS_KEY
        aws-region: $AWS_REGION
        aws-registry-id: $AWS_REGISTRY_ID
        repository: my_repo
```
But that doesn't work :(
I tried by user name and password, but I get always 
PUT https://xxxx.dkr.ecr.eu-west-1.amazonaws.com/v1/repositories/my_repo/ returned  404.
