### ISSUE TITLE
Instruction for pulling from GCR contains syntax error, and doesn't work

### ISSUE THREAD

**Issue by polymorpher** [wercker/docs#440]
The instructions for GCR section has syntax error: http://devcenter.wercker.com/docs/containers/private-containers.html

```
box:
    id: gcr.io/<MY-PROJECT-ID>/<MY-IMAGE>
        username: _json_key
        password: $GCR_JSON_KEY_FILE
        registry: https://gcr.io
        tag: <MY-IMAGE-TAG>
```

Should be 

```
box:
    id: gcr.io/<MY-PROJECT-ID>/<MY-IMAGE>
    username: _json_key
    password: $GCR_JSON_KEY_FILE
    registry: https://gcr.io
    tag: <MY-IMAGE-TAG>
```

In addition to that, this doesn't really work for me. I replaced <MY-PROJECT-ID>, <MY-IMAGE>, <MY-IMAGE-TAG> with proper values, and configured $GCR_JSON_KEY_FILE in global environment variables. It is reported in wercker that it cannot pull images from GCR because of 403 error.
